### ISSUE TITLE
Separate config for Dev and Prod

### ISSUE THREAD

**Issue by aiboy** [Angular-RU/angular-cli-webpack#1]
Separate config for Dev and Prod

**Comment by ivanpadavan** [comment]
Right now it is possible by writing:
```typescript
export default function(config, options) {
  //common config modification
  ...
  switch(options.buildOptions.enviroment) {
    case 'prod':
      config = productionModifications(config);
      break
    case 'dev':
      //etc
  }
}
```
So I think to leave things 'as is' in sake of simplicity (no configuration, no convention - just works). Sure there should be a FAQ that describes how to achieve frequent goals. So I'm about to close this issue. What do you think?)

**Comment by splincode** [comment]
Please add readme

**Comment by splincode** [comment]
I think it would be better to do so:

ngw-config.ts
```
export default function(config, options) {
  // common config modification
  // with automerged env config
}
```

ngw-config.dev.ts
```
export default function(config, options) {
  //dev config modification
}
```

ngw-config.prod.ts
```
export default function(config, options) {
  //prod config modification
}
```

Configs should already be ready in advance, just automatically connect as a middleware in a common configuration.ts

**Comment by ivanpadavan** [comment]
It's a bit more of convention. And, afterall, there could be much more possible configurations: testing, production, development, serving, building - a lot of options. They all described in options callback. Why should we split on env variable only?

**Comment by ivanpadavan** [comment]
Лучше не открывать ящик пандоры, ИМХО) Всё и так достижимо вполне компактным кодом

**Comment by splincode** [comment]
@aiboy @ivanpadavan I think the utility should have an interface for convenient configuration generation, if required

**Comment by ivanpadavan** [comment]
Я за то чтобы оставить пакет похожим на автомат Калашникова - простым и эффективным. Сейчас для обработки любого случая (хоть дополнительный аргумент придумать) занимает 3 строки. Из них две - это if, а одна это вызов функции с соседнего файла.

Если двигаться в направлении наращивания сложности, то потеряем в гибкости.

**Comment by splincode** [comment]
I understand, can then come up with a system of addons, so as not to change the engine, build up the presentation layer of the utility?

**Comment by ivanpadavan** [comment]
I'll focus on finding recepies for the tool. Surely it would be nice to have a cli, postinstall script that asks if you'd like to initialize package right now, some scraffolding and other stuff

**Comment by aiboy** [comment]
We need one of those:

1) An Example of how to handle Production and Dev cases (if we can do it inside ngw-config - it's fine for now but we need an example)
2) Separate dev, prod, staging etc.. files - overall it will be much better, but it's fine if we postpone this feature to "next" milestone

**Comment by splincode** [comment]
@aiboy Thank you, I'll take care of this.
