### ISSUE TITLE
Broken in the official Angular 6 release

### ISSUE THREAD

**Issue by larssn** [Angular-RU/angular-cli-webpack#19]
So the plugin doesn't work with the official release of Angular 6.

I've been looking into the API. It seems to be _completely_ different, *sigh*, so if this plugin is to continue working, a new approach has to be found.

What I've found so far is:
- The webpack config is now being built inside: `@angular-devkit/build-angular`
There's a function called: `buildWebpackConfig(root, projectRoot, host, options)`
in `@angular-devkit/build-angular/src/{browser, server, devserver}`.

I've tried using the old approach, but no luck so far... Lots of explosions.

Edit:
Allegedly this hack can be used if things are urgent: https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

**Comment by ivanpadavan** [comment]
Seems to be working now?

**Comment by larssn** [comment]
It does? Cool; I'll give it a try when I'm back at work! :-)
