### ISSUE TITLE
We found a potential security vulnerability in one of your dependencies.

### ISSUE THREAD

**Issue by splincode** [Angular-RU/angular-cli-webpack#20]
![image](https://user-images.githubusercontent.com/12021443/39863163-8f0e4838-544e-11e8-9f48-96db19a70aae.png)

**Comment by ivanpadavan** [comment]
The issue is with some of deep @angular/cli dependencies. The mistake was to push package-lock file into repository. As you know this package relies only on `ts-node`. So don't see any problems with that.
