### ISSUE TITLE
Set up script doesn't update chained commands.

### ISSUE THREAD

**Issue by tplk** [Angular-RU/angular-cli-webpack#26]
When multiple commands are used in a script set up script only changes the first one.
Example:
```
ng lint app && ng test app --watch=false
```
results in
```
ngw lint app && ng test app --watch=false
```

**Comment by ivanpadavan** [comment]
Yeah, and it won't. There could be unexpectendly complicated stuff that could be broken by automatiation. So manual renames for complex cases

**Comment by tplk** [comment]
@ivanpadavan got it, thanks. It would be reasonable to mention it in readme too.

But I also think that it's possible to handle more complex cases too. For example, we can match `ng` followed by a command from the predefined list of cli commands (or maybe parse it on the fly from `ng help` output):
```regex
(^|\|\| |&& )ng (add|new|generate|update|build|serve|test|e2e|lint|xi18n|run|eject|config|help|version|doc)
```
