### ISSUE TITLE
How to push to modules.export in webpack.config.js

### ISSUE THREAD

**Issue by Prathik-Jain** [Angular-RU/angular-cli-webpack#28]
I want to add a line to `modules.export` in the webpack configuration - how do I do that?

**Comment by splincode** [comment]
We usage webpack.config.ts in TypeScript when running ng cli

```ts
export default function(config) {

}
```

analog module.export

**Comment by Prathik-Jain** [comment]
```ts
export default function(config) {
        config.module.export.push({
             //My line of code
         });
}
```
This is what you mean by analog ?
An example would be great if I am wrong.

**Comment by Prathik-Jain** [comment]
its `config.mode = 'production';`
