### ISSUE TITLE
Passing parameters for node instance

### ISSUE THREAD

**Issue by madbonez** [Angular-RU/angular-cli-webpack#33]
Hi, i'am faced with this issue on angular-cli
https://github.com/angular/angular-cli/issues/5618

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

mostly there guys says use this workaround for adjusting nodejs
 --max-old-space-size=8192
but now its not possible , because params cant be pass naturally

I suggest that approach below will be good solution. looks like passing params to npm scripts (double dash)
for example:
ngw --prod --aou=false  -- --max-old-space-size=8192

**Comment by madbonez** [comment]
I make PR look it please

**Comment by madbonez** [comment]
Usage example"build": "ngw -- --max_old_space_size=4096 build --prod --aot=false",

**Comment by ivanpadavan** [comment]
That's all cool, but not related with purpose of this package. How you'll solve this problrm with `ng` command which doesn't work with `ngw`? Did you try that? https://github.com/npm/npm/issues/12238#issuecomment-367147962

**Comment by madbonez** [comment]
Yeah you rigth. Solution that you provide work perfectly! Closing issue
