### ISSUE TITLE
Support Angular 7

### ISSUE THREAD

**Issue by domi7777** [Angular-RU/angular-cli-webpack#40]
It would be nice that ngw is compatible with Angular 7 so we can upgrade our project.

**Comment by ivanpadavan** [comment]
I use it with angular 7 projects

**Comment by domi7777** [comment]
@ivanpadavan , If I understand correctly it's already compatible with Angular 7?

Should the **README.md** state that it is?

**Comment by ivanpadavan** [comment]
Agree with you. #41 #42
