### ISSUE TITLE
Support Angular 8

### ISSUE THREAD

**Issue by Svetomech** [Angular-RU/angular-cli-webpack#45]
Currently it fails with following error when using Angular 8:

![image](https://user-images.githubusercontent.com/7114815/61311552-3f2e2a80-a7ff-11e9-9219-fab2a2f22475.png)

Also **NormalizedBrowserBuilderSchema** doesn't seem to exist in Angular 8.

![image](https://user-images.githubusercontent.com/7114815/61311605-5836db80-a7ff-11e9-85ff-3268044033ee.png)

**Comment by splincode** [comment]
`angular-cli-webpack` - deprecated, use https://www.npmjs.com/package/@angular-builders/custom-webpack
