### ISSUE TITLE
ngw build not working in angular 9

### ISSUE THREAD

**Issue by akshata456** [Angular-RU/angular-cli-webpack#46]
When i did migration from angular7.1.4 to angular 9 ,ngw build get failed.
environment:
 "@angular-devkit/build-angular": "~0.901.12",
"@angular/cli": "~9.1.12"
"@angular/compiler-cli": "~9.1.12",
"ngw": "^7.0.0",
"typescript": "^3.8.3",
 "webpack-cli": "^3.2.3"

error is:
TypeError: Cannot read property 'prototype' of undefined
    at buildConfig (D:\careclues-ui-v9\careclues-angular\node_modules\ngw\lib\index.js:22:45)

**Comment by ivanpadavan** [comment]
Angular's build system changed dramatically and become more flexible. You
can use https://www.npmjs.com/package/@angular-builders/custom-webpack now.
I'm wishing you easy update!

чт, 27 авг. 2020 г., 17:12 GA <notifications@github.com>:

**Comment by akshata456** [comment]
@ivanpadavan i follow all steps for custom-webpack but not it reproduced new issue during ng build like 
ERROR in Could not resolve module D:/careclues-ui-v9/careclues-angular/src/app/app.browser.module.ts
Previously ng build is working fine but error during ngw build --prod.Now after adding custom-webpack ng build get broked.
can you give any suggestion here?Thanks.

  "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "indexTransform": "src/index-html-transform.js",
            "outputPath": "dist/browser",
            "index": "src/index.html",
            "main": "src/main.browser.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.browser.json",

tsconfig.json:
{
  "extends": "../tsconfig.json",
  "angularCompilerOptions": {
    "entryModule": "../src/app/app.browser.module.ts#AppBrowserModule"
},
  "compilerOptions": {
    "outDir": "../out-tsc/browser",
    "types": [
      "googlemaps"
    ]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by akshata456** [comment]
@ivanpadavan  "ngw serve" gives error same then what we used any alternatives for ngw in angular 9
 var methodName = configClasses[variant].prototype.hasOwnProperty('_buildWebpackConfig')
                                            ^
TypeError: Cannot read property 'prototype' of undefined
